version: '3.8'

services:
  # MongoDB数据库服务
  mongodb:
    image: mongo:4.4
    container_name: photo-gallery-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: photo_gallery_2024
      MONGO_INITDB_DATABASE: photo_gallery
    volumes:
      # 群晖路径映射 - 持久化数据库数据
      - /volume1/docker/photo-gallery/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - photo-network

  # 后端API服务
  api:
    image: ghcr.io/binbin1213/photo-gallery-backend:latest
    container_name: photo-gallery-api
    restart: unless-stopped
    ports:
      - "5551:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      UPLOAD_PATH: /app/uploads
      # MongoDB连接配置
      MONGODB_URI: mongodb://admin:photo_gallery_2024@mongodb:27017/photo_gallery?authSource=admin
      DB_NAME: photo_gallery
    volumes:
      # 群晖路径映射 - 需要根据实际情况调整
      - /volume1/docker/photo-gallery/photos:/app/uploads/photos:ro
      - /volume1/docker/photo-gallery/data:/app/data
      - /volume1/docker/photo-gallery/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - photo-network

  # 前端服务
  photo-gallery-frontend:
    image: ghcr.io/binbin1213/photo-gallery-frontend:latest
    container_name: photo-gallery-frontend
    restart: unless-stopped
    ports:
      - "8881:80"
    depends_on:
      - api
    networks:
      - photo-network

networks:
  photo-network:
    driver: bridge
