name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./client
        push: false
        tags: photo-gallery-frontend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build backend image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        push: false
        tags: photo-gallery-backend:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test docker-compose
      run: |
        docker-compose config
        echo "✅ Docker Compose configuration is valid"

    - name: Build with docker-compose
      run: |
        docker-compose build
        echo "✅ All images built successfully"

    - name: Show image sizes
      run: |
        docker images | grep photo-gallery
